package com.example.stech_buddies

// Represents request body for OpenAI API
data class GPTRequestBody(
    val model: String, // Specifies model to be used
    val messages: List<GPTMessage>, // List of messages forming conversation context
    val max_tokens: Int // Maximum nb of tokens allowed in response
)

// Represents an individual message in conversation
data class GPTMessage(
    val role: String, // Role of the sender: "system", "user", or "assistant"
    val content: String // content of the message
)

// Represents response received from the OpenAI API
data class GPTResponse(
    val choices: List<GPTChoice> // List of possible response choices from model
)

// Represents a single choice in the response
data class GPTChoice(
    val message: GPTMessage // The actual response message generated by the model
)
